### ISSUE TITLE
Text error

### ISSUE THREAD

**Issue by dn-scribe** [rung/threat-matrix-cicd#5]
Hi,
In the execution table, SCA was interpreted as "Security Compliance Associates" This is a name of a consulting company....
I think is should be Source Code Analysis.

Thanks, and thanks for the good work

**Comment by BtrYrSlf** [comment]
I recommend avoiding any use of SCA to represent Source Code Analysis because SCA is so often (and more often in my experience) used to represent Software Composition Analysis. If there is some place for source code analysis, I recommend instead using the more specific terms SAST and/or DAST.

**Comment by dn-scribe** [comment]
I think you are right - SCA should be Software Component Analysis - this indeed is a way to deal with (known) bad dependencies.

Anyways, "Security Compliance Associates" should be fixed.

**Comment by rung** [comment]
Thanks! I fixed it.
